### ISSUE TITLE
Java 21 crash: `UnsupportedOperationException: Boot class path mechanism is not supported`

### ISSUE THREAD

**Issue by Krutoy242** [friendlyhj/ProbeZS#7]
Im trying to launch my modpack `E2E-E` on [CleanroomMMC](https://github.com/CleanroomMC/CleanroomMMC) (Java 21). I know its experemental thing and not even widely published and tested yet, but I want to report issue anyway - maybe it will be handy in future.

```ruby
net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from ProbeZS (probezs)
Caused by: java.lang.UnsupportedOperationException: Boot class path mechanism is not supported
    at sun.management.RuntimeImpl.getBootClassPath(Unknown Source)
    at youyihj.probezs.ProbeZS.dumpEnvironment(ProbeZS.java:338)
    at youyihj.probezs.ProbeZS.onPreInit(ProbeZS.java:153)
    at jdk.internal.reflect.DirectMethodHandleAccessor.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:637)
```

[crash-2024-02-11_12.08.10-client.txt](https://github.com/friendlyhj/ProbeZS/files/14231835/crash-2024-02-11_12.08.10-client.txt)

**Comment by friendlyhj** [comment]
Update ProbeZS. It has fixed in `v1.17.9`.
