### ISSUE TITLE
FML ERROR: `ProbeZS-1.18.3.jar - probably a corrupt zip`

### ISSUE THREAD

**Issue by Krutoy242** [friendlyhj/ProbeZS#8]
Loading game with ProbeZS output this errors in debug.log file:

```ruby
[Client thread/ERROR] [FML]: There was a problem reading the entry META-INF/versions/9/module-info.class in the jar E:\mc\packs\E2E-E\minecraft\mods\ProbeZS-1.18.3.jar - probably a corrupt zip
net.minecraftforge.fml.common.LoaderException: java.lang.IllegalArgumentException

	at net.minecraftforge.fml.common.discovery.asm.ASMModParser.<init>(ASMModParser.java:63) ~[ASMModParser.class:?]
```

```ruby
[Client thread/DEBUG] [FML]: Identified a mod of type Lnet/minecraftforge/fml/common/Mod; (youyihj.probezs.ProbeZS) - loading
[Client thread/TRACE] [FML]: Parsed dependency info for probezs: Requirements: [crafttweaker] After:[crafttweaker] Before:[]
[Client thread/ERROR] [FML]: Unable to read a class file correctly
```

And this warning:
```ruby
[Client thread/WARN] [FML]: Zip file ProbeZS-1.18.3.jar failed to read properly, it will be ignored
net.minecraftforge.fml.common.LoaderException: java.lang.IllegalArgumentException

	at net.minecraftforge.fml.common.discovery.asm.ASMModParser.<init>(ASMModParser.java:63) ~[ASMModParser.class:?]
```

What does this means? If this have no effect on game and can be ignored?

[debug.log](https://github.com/friendlyhj/ProbeZS/files/14663893/debug.log)

**Comment by friendlyhj** [comment]
ProbeZS contains `snakeyaml` lib, which has `module-info` file for java 9+ compat. Forge scans all java files of mod jar. Since `module-info` is java 9+ stuff, Forge on Java 8 platform doesn't recogize it and log a warning. The warning can be ignored, but I should find a way to exclude the file from mod jar.
